fosslight-oss/if-you-are-rich-then-do-not-solve-algorithm

hello70825/programmers_87946.py

[231013] feat: solve 프로그래머스 - 피로도

---

hello70825/programmers_138476.py
hello70825/programmers_142085.py
hello70825/programmers_154539.py

[231014] feat: solve 프로그래머스 - 뒤에 있는 큰 수 찾기, 디펜스 게임, 귤 고르기

---

jiwon83/BOJ_1543_문서검색.java
jiwon83/BOJ_2661_좋은수열.java

[231014] feat: BOJ_1543_문서검색

---

hello70825/programmers_132265.py

[231016] feat: solve 프로그래머스 - 롤케이크 자르기

---

hello70825/programmers_131704.py
hello70825/programmers_135807.py

[231017] feat: solve 프로그래머스 - 숫자 카드 나누기, 택배상자

---

hello70825/programmers_131701.py

[231018] feat: solve 프로그래머스 - 연속 부분 수열 합의 개수

---

hello70825/BOJ_25167.py

[231019] feat: solve BOJ - 이상한 아리의 채점

---

hello70825/programmers_12903.java

미션도 해야하고... 이력서는 다시 만들고... 자소서까지 쓰니까 문제 풀 시간이 없네요

[231027] feat: solve 프로그래머스 - 가운데 글자 가져오기

---

hello70825/programmers_86971.py

[231031] feat: solve 프로그래머스 - 전력망을 둘로 나누기

---

hello70825/programmers_70129.py

[231101] feat: solve  프로그래머스 - 이진 변환 반복하기

---

hello70825/programmers_68936.py

[231102] feat: solve 프로그래머스 - 쿼드압축 후 개수 세기

---

d0ri123/Programmers26.java

[231103] feat: solve 프로그래머스 - 카펫

---

hello70825/programmers_42747.py

[231104] feat: solve 프로그래머스 - H-index

---

hello70825/programmers_12914.py

[231107] feat: solve 프로그래머스 - 멀리 뛰기

---

hello70825/programmers_43162.py

[231108] feat: solve 프로그래머스 - 네트워크

---

hello70825/programmers_12927.py

[231110] feat: solve 프로그래머스 - 야근 지수

---

hello70825/programmers_12938.py

[231111] feat: solve 프로그래머스 - 최고의 집합

---

hello70825/programmers_43163.py

[231112] feat: solve 프로그래머스 - 단어 변환

---

hello70825/programmers_42898.py

유명한 DP 문제긴한데, 작년 SKT에서 똑같은 유형으로 어려운 조건 1개 추가해서 코테에 나왔었어요

[231113] feat: solve 프로그래머스 - 등굣길

---

hello70825/programmers_12917.py

[231115] feat: solve 프로그래머스 - 문자열 내림차순으로 배치하기

---

hello70825/programmers_64061.py
hello70825/programmers_64062.py
hello70825/programmers_64063.py
hello70825/programmers_64064.py
hello70825/programmers_64065.py
hello70825/programmers_67256.py
hello70825/programmers_67257.py
hello70825/programmers_67258.py
hello70825/programmers_67259.py

[231122] feat: solve 프로그래머스 - 카카오 인턴 기출 (2018 ~ 2020)

---

suheoon/boj_2530.cpp
suheoon/boj_2914.cpp

[231204, 231205] solve 백준 인공지능시계, 저작권 풀이

---

hello70825/programmers_42861.py

크루스칼 알고리즘이 그리디 알고리즘이라는걸 이제 처음 알았네요 ㄷㄷ
단순 정렬만 해도 그리디라니

[231208] feat: solve 프로그래머스 - 섬 연결하기

---

dener8/programmers_무인도여행.py

1. 파이썬은 최대 재귀 depth가 1000 
```
import sys
sys.setrecursionlimit(n)
```
2. 재귀, dfs.. 진짜 꾸준히 못함 🤬

[231210] feat: solve programmers 무인도여행

---

dener8/boj_3190_뱀.py
dener8/programmers_택배상자.py

deque은 list보다 삽입/삭제 시간이 빠른 반면,
인덱스 접근 속도는 느리다.
list - O(1)
deque - O(N)
삽입/삭제가 잦은 경우 -> deque 사용
인덱스 접근이 잦은 경우 -> list 사용

[231212] feat: solve boj 3190 뱀, programmers 택배상자

---

dener8/programmers_도둑질.py

DP 풀 때는 **최대한 작은 범위**부터 생각하기
&
그 뒤의 일은 뒤에서 해결되겠지~ 라는 마음으로 점화식 세우기

[231215] feat: solve programmers 도둑질

---

dener8/programmers_N으로표현.py

[231217] feat: solve programmers N으로표현

---

dener8/boj_16236_아기상어.py

시뮬은 디버깅이 너무 어렵다.. 처음부터 차근차근 생각한 후 코드 작성하기 ✏️

[240103] feat: solve boj 16236 아기상어

---

jiwon83/BOJ_10546_기적의매매법.java
jiwon83/BOJ_10799_쇠막대기.java
jiwon83/BOJ_2753_윤년.java

[240129] feat: solve BOJ 10799 쇠막대기
